version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-north-1"
profile = "lisa.arvidsson@knowit.se"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true