package dto;

public enum PayloadType {
    POWER_LIMIT_ACKNOWLEDGEMENT,
    CONSUMPTION_POWER_LIMIT,
    POWER_LIMIT_VALIDATION_STATUS,
    POWER_LIMIT_VALIDATION_TIMESTAMP,
    POWER_LIMIT_VALIDATION_READING,
    POWER_LIMIT_VALIDATION_STATUS_TEXT
}